### PR TITLE
cleanup the  test deploy script

### PR DESCRIPTION
**Pull request by krasi-georgiev**
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by krasi-georgiev** [comment]
@themandalore why did you close it?

**Comment by themandalore** [comment]
the tests were failing and tbh the whole mock deployment thing is sort of a non-issue now.  It's much easier just to fork mainnet and then if you want to turn off a given feature (e.g. the 12 hour limit), just fork the contracts

**Comment by krasi-georgiev** [comment]
I understand, but you should have at least one working script for a full deployment no?

Can you point me to a script that deployed a full tellor system from scratch?

**Comment by tkernell** [comment]
This one will do that: https://github.com/tellor-io/tellorX/blob/main/scripts/deploy2.js

**Pull request merged**
